name: ci-cd

on:
  push:
    branches: 
      - '!master'
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        
    steps: 
      - name: Fetch Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --frozen-lockfile
      - name: Execute tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: test
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        
    steps: 
      - name: Execute tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: coverage
