name: ci-cd

on:
  push:
    branches: 
      - '!master'
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: unit test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        
    steps: 
      - name: Fetch code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --frozen-lockfile
      - name: Execute tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
      - name: Archive unit tests report
        uses: actions/upload-artifact@v1
        with:
          name: unit-test-report
          path: reports

  coverage:
    name: code coverage
    runs-on: ubuntu-latest
    needs: test
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        
    steps: 
      - name: Fetch code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --frozen-lockfile
      - name: Execute coverage
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: coverage
      - name: Archive code coverage report
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage

  lint:
    name: lint code
    runs-on: ubuntu-latest
    needs: coverage
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        
    steps: 
      - name: Fetch code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --frozen-lockfile
      - name: Execute coverage
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
