name: ci-cd

on:
  push:
    branches: 
    - master
    - 'bsmrk-**'
  pull_request:
    branches: 
      - master         # Push events on master branch
      - 'bsmrk-**' # Push events to branches matching refs/heads/mona/octocat

jobs:
  test:
    name: Testing Code
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        
    steps: 
      - name: Fetching code from repo/branch
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --frozen-lockfile
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
